var express = require('express');
var app = express();
app.use(express.static('public'));
var cities = require('./routes/cities');
app.use('/cities', cities);
var blocks = require('./routes/blocks');
app.use('/blocks', blocks);
var parts = require('./routes/parts');
app.use('/parts', parts);
module.exports = app;